"""Initial migration upgrade borrow

Revision ID: caa4483dd053
Revises: 37cd19f58271
Create Date: 2024-12-11 14:34:46.124577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa4483dd053'
down_revision: Union[str, None] = '37cd19f58271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrows', 'return_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrows', 'return_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
